name: ChainX Explorer Deployment

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  chainx2-scan-deploy:
    # Name the Job
    name: Deploy chainx2-scan
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      # - name: Checkout code
      #  uses: actions/checkout@v2

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
          BRANCH: "develop"
        with:
          hosts: 'root@8.210.209.20'
          privateKey: ${{ secrets.PRIVATE_KEY }}
          debug: false
          command: |
            ls -lah
            echo "I am $NAME"
            pm2 status
            free
            cd chainx2-scan
            git checkout -b temp
            git checkout develop
            eval $(ssh-agent)
            ssh-add ~/.ssh/chainx2scan_rsa
            git pull
            cd packages
            git diff --quiet HEAD temp -- scan || pm2 restart explorer-scan
            git diff --quiet HEAD temp -- server || pm2 restart explorer-server
            git diff --quiet HEAD temp -- site || pm2 restart explorer-site
            git branch -d temp
            pm2 status
